services:
  app:
    build: .
    command: npm run dev
    networks:
      - net
    depends_on:
      - mongodb
    ports:
      - "${PORT}:${PORT}"
    volumes:
      - .:/home/app
      - /home/app/node_modules

  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - net
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

networks:
  net:
